### PR TITLE
SODEV-6448 add ios-list

### PR DESCRIPTION
**Pull request by markholmes**
Please ask another designer/developer to merge your pull request.

# Pre-Merge Checklist
- [ ] Committed the latest version of `cheatsheet.html` with my changes
- [ ] Included Jira reference in commit message (if applicable)
- [x] Using [semver](http://semver.org/), increment the version number in the [`package.json`](https://github.com/buildcom/ionicons/blob/master/package.json#L3)

# Post-Merge Checklist

- [ ] [Create a new release](https://help.github.com/articles/creating-releases/)
- [ ] Have a UX designer update the [Frontify styleguide](https://company-47402.frontify.com/d/JC5zNa6KOQ2r/brand-guidelines#/brand-styleguide/icons)

### CODE REVIEW

**Comment by tmjam** [comment]
@markholmes I still feel the cheat sheet should be kept updated.

**Comment by mikebm** [comment]
Cheat Sheet is built off of the fonts and not SVG's, so unless we plan on manually adding SVG's to it...

**Comment by tmjam** [comment]
gotcha could be a follow-up thing we can update the cheat sheet to use SVG

**Comment by markholmes** [comment]
@mikebm @tmjam is there anything I need to add to this PR?

**Pull request merged**
